### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by Ecatombe86** [edzillion/blood-n-guts#39] opened 2020-10-23 15:04 UTC
Hi,
after I leave the game or reload it, the custom settings I made, get back to the default ones.
I'm on 7.5.0

**Comment by edzillion** [comment] 2020-10-23 15:11
Hmmm. I can't reproduce. I have set a custom setting, reloaded the world it's there, reloaded the server it's still there. 

Two thoughts:
1. If you set a violence level it will reset custom settings. 
1. If you close the window without hitting 'submit' it won't save either.

**Comment by Ecatombe86** [comment] 2020-10-23 20:15
Seems weird, it doesn't happen to me neither anymore.
I didn't even restart the PC.
I'll let you know if the problem presents again.
Thanks

**Comment by amcvfx** [comment] 2020-10-27 12:23
Hey! I am still getting this issue. I can't be sure where it happens, either reloading my browser or making changes to other module settings? But it seems to reset back to the preset from the Violence Level drop down menu and not my custom settings.

**Comment by Ecatombe86** [comment] 2020-11-01 20:28
I can confirm it happens sometimes, still can't correctly reproduce it.

**Comment by edzillion** [comment] 2020-11-01 20:44
Ok thanks @Ecatombe86 I haven't seen this but will keep an eye out - my one thought it that it is from updating the module?

**Comment by amcvfx** [comment] 2020-11-17 15:02
I can confirm that updating to module version 0.6.7 reset the settings. I find that almost every time I start a new session though I need to check and update my custom settings.

**Comment by edzillion** [comment] 2020-11-22 10:24
Can you test with latest (0.6.10) - I did a big overhaul of the settings system and it should be a bit more robust now.

**Comment by edzillion** [comment] 2020-11-27 08:42
I am going to close this as the settings system has been changed quite a bit. If this issue keeps occurring feel free to reopen

**Closed by edzillion** 2020-11-27 08:42 UTC
Labels: bug
