### ISSUE TITLE
BUG: Token Configuration gets wonky with this module

### ISSUE THREAD

**Issue by GambetTV** [edzillion/blood-n-guts#192] opened 2021-02-02 08:38 UTC
Blood Color, and Light Color (under the vision tab) don't show their color when first launching a Token's Configuration screen. Changing the Light Color works fine, but you don't get a preview of the color anymore. When you click on Blood Color (under Image) it immediately populates with color, and fixes the Light Color preview bar as well, but it goes away the next time you launch it.

Also, if you close the Token Configuration window while under the Image Tab, when you reopen it, it will not open to its maximum size, and half the window will be cut off. This is easily fixed by switching tabs, but it's still an issue.

**Comment by edzillion** [comment] 2021-02-25 11:10
I believe this is fixed in the latest version (0.8.0) which I am currently testing. I have simplified the whole colour system and have gotten rid of a hacky bit of code that tried to set the alpha level of those colour picker preview boxes. It's likely that caused the problem.

I cannot recreate the layout issue you describe, perhaps it was caused by the above.

**Closed by edzillion** 2021-02-25 11:10 UTC
