### ISSUE TITLE
Consistently Inconsistent colours with PF2e NPCs

### ISSUE THREAD

**Issue by DuskyVoltage** [edzillion/blood-n-guts#121] opened 2020-11-17 23:13 UTC
lookupTokenBloodColour for certain types of creature alternates between the correct colour of blood and "undefined".
Have tested with various types 
Undead: Skeletal Champion, Skeletal Giant, Skeleton Guard; 
Plants: Leaf Leshy, Gourd Leshy; 
Constructs: Adamantium Golem, Flesh Golem, Iron Golem

Creatures such as Animals or Humanoids consistently return the correct "blood" colour, Characters also seem fine.
The faulty behaviour occurs even with the same actor dragged onto the map multiple times in a row.
Console outputs:
[Undead](https://i.imgur.com/hqtoOsY.png)
[Plant](https://i.imgur.com/TVpyvYU.png)
[Construct](https://i.imgur.com/rFKGXPO.png)

Behaviour still occurs when Blood N Guts is the only active module

**Comment by edzillion** [comment] 2020-11-26 18:26
I think this is a dupe of #152 and should be fixed in latest 0.7.1 #156

**Closed by edzillion** 2020-11-26 18:26 UTC
Labels: bug
